### ISSUE TITLE
Move to Loomio community plan

### ISSUE THREAD

**Issue by Gareth-RL** [osm-uk/TODO#13]
Our subscription renews on 26th January. We have no paid staff and qualify as a volunteer community group. Move to the $199 lifetime plan.

**Comment by jnicho02** [comment]
<img width="1082" alt="Screenshot 2022-01-20 at 09 54 44" src="https://user-images.githubusercontent.com/83251/150315619-b30115d4-e07b-4866-8341-e730a82823be.png">
