### ISSUE TITLE
Jan 2022: Loomio subscription

### ISSUE THREAD

**Issue by RobJN** [osm-uk/TODO#2]
Move to the lifetime subscription at end of current period.

**Comment by Cj-Malone** [comment]
Do we know when the current period ends?

**Comment by RobJN** [comment]
We need to complete this task by 26 Jan 2022 as that is when the large renewal payment goes out:

>Your current plan: Community Annual is due to renew on 2022-01-26 for $114 USD (plus sales tax if applicable) 

Having said that, it does state:

>We have recently introduced new subscription plans, you can change to a new plan at any time. Any remaining credit on your previous plan will be carried to your new plan.

**Comment by Cj-Malone** [comment]
We've already voted on this, and with the credit roll over I think who ever has access to that part of Loomio should do it now before we forget.

**Comment by jnicho02** [comment]
duplicated in #13 (and done by Jon)
