### ISSUE TITLE
ICO tax

### ISSUE THREAD

**Issue by Cj-Malone** [osm-uk/TODO#9]
I don't believe we need to pay [it](https://ico.org.uk/for-organisations/data-protection-fee/self-assessment/y/N/Y/Yes/Yes/No/Yes), if we all agree we'll probably need to notify them to stop the letters.

**Comment by adam-pasabi** [comment]
There's a form to fill in on their website to register as exempt. https://ico.org.uk/for-organisations/data-protection-fee/exemptions/

**Comment by atomoil** [comment]
There's a form to fill in on their website to register as exempt. https://ico.org.uk/for-organisations/data-protection-fee/exemptions/

**Comment by Cj-Malone** [comment]
Any updates on this @spiffygit ?
